---
- hosts: nodes
  user: root
  become: yes
  tasks:
  - name: Install Apache
    yum: name=httpd state=latest
  - name: start service
    service: name=httpd state=started enabled=yes
  - name: Install dns
    yum: name=bind state=latest
  - name: start service
    service: name=named state=started enabled=yes
